config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "calendar#index"

  get "/reminder/:month/:day/:year", to: "calendar#show"
  get "/reminder/:month/:day/:year/new", to: "calendar#new"
  get "/reminder/:id/edit", to: "calendar#edit"
  post "/reminder", to: "calendar#save"
  patch "/reminder/:id", to: "calendar#update"
  delete "/reminder/:id", to: "calendar#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reminder.rb
class Reminder < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  validates :color, presence: true
  validates :scheduled_datetime, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def render_error(code)
    respond_to do |format|
      format.html { render :file => "#{Rails.root}/public/#{code}.html", :layout => false, :status => :not_found }
      format.xml { head :not_found}
      format.any { head :not_found }
    end
  end
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def initialize
    @date = DateTime.now
    @today = DateTime.now
    @date_string = @date.strftime("%A, %B %d, %Y")
    @first_day_wday = 0
    @reminder_days = Array.new
    @REMINDER_COLORS = ['#C8E6C9', '#F5DD29', '#FFCC80', '#EF9A9A', '#CD8DE5', '#5BA4CF', '#29CCE5', '#6DECA9', '#FF8ED4', '#BCAAA4']
  end

  def index
    now = DateTime.now
    redirect_to "/reminder/#{now.month}/#{now.day}/#{now.year}"
  end

  def reset_date_values(year, month, day)
    @date = Date.new(year, month, day)
    @date_string = @date.strftime("%A, %B %d, %Y")
    @first_day_wday = Date.new(year, month, 1).wday
    @reminder_days = Reminder.where(scheduled_datetime: Date.new(year, month, 1)..Date.new(year, month, -1)).map { |reminder| reminder.scheduled_datetime.day }
  end

  def show
    begin
      reset_date_values(params[:year].to_i, params[:month].to_i, params[:day].to_i)
      date_reminders = Reminder.where(scheduled_datetime: @date.beginning_of_day..@date.end_of_day).order(:scheduled_datetime)
      if (date_reminders.empty?)
        raise ActiveRecord::RecordNotFound
      end

      render layout: "application", template: "calendar/show", :locals => {:date_reminders => date_reminders}
    rescue ActiveRecord::RecordNotFound => e
      render layout: "application", template: "calendar/empty"
    rescue Exception => e
      render_error(500)
    end

  end

  def new
    begin
      reset_date_values(params[:year].to_i, params[:month].to_i, params[:day].to_i)

      render layout: "application", template: "calendar/edit", :locals => {:mode => "add"}
    rescue ActiveRecord::RecordNotFound => e
      render layout: "application", template: "calendar/empty"
    end
  end

  def update
    begin
      reminder = Reminder.find_by!(id: params[:id])
      reminder.title = params[:title]
      reminder.description = params[:description]
      reminder.color = params[:color]
      reminder.scheduled_datetime = DateTime.strptime(params[:reminder_date] + 'T' + params[:reminder_time], "%m/%d/%YT%I:%M %p")
      reminder.save!

      render json: {}, status: 200
    rescue Exception => e
      render json: {'error' => e.message}, status: 500
    end
  end

  def save
    begin
      scheduled_datetime = DateTime.strptime(params[:reminder_date] + 'T' + params[:reminder_time], "%m/%d/%YT%I:%M %p")

      reminder = Reminder.new
      reminder.title = params[:title]
      reminder.description = params[:description]
      reminder.color = params[:color]
      reminder.scheduled_datetime = scheduled_datetime
      reminder.save()
      render json: reminder, status: 200
    rescue Exception => e
      puts e.message
      render json: {'error' => e.message}, status: 500
    end
  end

  def edit
    begin
      reminder = Reminder.find_by!(id: params[:id])
      reset_date_values(reminder.scheduled_datetime.year, reminder.scheduled_datetime.month, reminder.scheduled_datetime.day)

      render layout: "application", template: "calendar/edit", :locals => {:mode => "edit", :reminder => reminder}
    rescue ActiveRecord::RecordNotFound => e
      render_error(404)
    rescue Exception => e
      render_error(500)
    end
  end

  def destroy
    begin
      Reminder.where(id: params[:id]).destroy_all
      render json: {}, status: 200
    rescue Exception => e
      render json: {'error' => e.message}, status: 500
    end
  end

  private
    def calendar_params
      params.permit(:id, :title, :description, :color, :reminder_date, :reminder_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/views/calendar/edit.html.erb
<div class="flex flex-row justify-between items-center">
  <p class="font-sans font-semibold text-2xl text-[#384042]">
    <%= mode == "add" ? "Add" : "Edit" %> reminder - <%= @date_string %>
  </p>
</div>

<% reminder_show_url = "/reminder/#{@date.month}/#{@date.day}/#{@date.year}" %>
<input id="reminder_id" type="hidden" value="<%= mode =='edit' ? reminder.id : '' %>" />
<input id="mode" type="hidden" value="<%= mode %>" />
<input id="show_url" type="hidden" value="<%= reminder_show_url %>" />

<div class="mt-[22px]">
  <label for="calendar_title" class="font-sans block mb-px text-lg font-normal text-[#384042]">Title</label>
  <input type="text" id="calendar_title" class="peer bg-white border border-gray-300 text-gray-900 text-smrounded-lg rounded-md focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" placeholder="Title" value="<%= mode == 'edit' ? reminder.title : '' %>" required>
  <p class="error invisible text-red-700 font-light">
    Please enter a title
  </p>
</div>

<div class="mt-[30px]">
  <label for="calendar_description" class="font-sans block mb-px text-lg font-normal text-[#384042]">Description</label>
  <textarea type="text" row="3" id="calendar_description" class="peer bg-white border border-gray-300 text-gray-900 text-smrounded-lg rounded-md focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" placeholder="Description" required><%= mode == 'edit' ? reminder.description : '' %></textarea>
  <p class="error invisible text-red-700 font-light">
    Please enter a description
  </p>
</div>

<div class="flex flex-row justify-between mt-[30px]">
  <div class="grow">
    <label for="reminder_date" class="font-sans block mb-px text-lg font-normal text-[#384042]">Date</label>
    <div class="datepicker relative form-floating mb-3" data-mdb-toggle-button="false" data-mdb-format="mm/dd/yyyy">
      <input type="text" id="reminder_date"
        class="peer form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
        placeholder="MM/DD/YYYY" data-mdb-toggle="datepicker" value="<%= mode == 'edit' ? reminder.scheduled_datetime.strftime("%m/%d/%Y") : '' %>" />
      <label for="floatingInput" class="text-gray-700">MM/DD/YYYY</label>
      <p class="error invisible text-red-700 font-light">
        Please select a date
      </p>
    </div>
  </div>

  <div class="w-[40px]">
  </div>
  <div class="grow">
    <label for="reminder_time" class="font-sans block mb-px text-lg font-normal text-[#384042]">Time</label>
    <div class="timepicker relative form-floating mb-3 xl:w-96" data-mdb-with-icon="false" data-mdb-format="hh:mm" id="input-toggle-timepicker">
      <input type="text" id="reminder_time"
        class="peer form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
        placeholder="HH:MM" data-mdb-toggle="input-toggle-timepicker" value="<%= mode == 'edit' ? reminder.scheduled_datetime.strftime("%I:%M %p") : '' %>" />
      <label for="floatingInput" class="text-gray-700">HH:MM</label>
      <p class="error invisible text-red-700 font-light">
        Please select a time
      </p>
    </div>
  </div>
</div>

<div class="flex flex-col mt-[30px] color-boxes">
  <label class="font-sans block mb-px text-lg font-normal text-[#384042]">Color</label>
  <div class="flex justify-between">
    <% @REMINDER_COLORS.each { |color| %>
      <button class="w-[55px] h-[48px] color-border bg-[<%= color %>] btn-color <%= mode == 'edit' && color.downcase == reminder.color.downcase ? 'color-selected-border' : '' %>"></button>
    <% } %>
  </div>
  <p class="error invisible text-red-700 font-light">
    Please select a color
  </p>
</div>

<div class="flex flex-col mt-[50px] border-t border-[rgba(49, 39, 37, 0.2)]"></div>

<div class="flex flex-row justify-<%= mode == 'add' ? "end" : 'between' %> mt-[40px]">
  <% if mode == 'edit' %>
    <button class="btn btn-remove bg-red">Remove</button>
  <% end %>
  <div>
    <a class="btn btn-cancel bg-grey" href="<%= reminder_show_url %>">Cancel</a>
    <button class="btn btn-save bg-blue ml-[14px]">Save</button>
  </div>
</div>

app/views/calendar/empty.html.erb
<div class="flex flex-row justify-between items-center">
  <p class="font-sans font-semibold text-2xl text-[#384042]">
    <%= @date_string %>
  </p>
  <a class="btn bg-primary" href="<%= "/reminder/#{@date.month}/#{@date.day}/#{@date.year}/new" %>">
    Add reminder
  </a>
</div>

<div class="flex flex-col items-center mt-[128.8px]">
  <%= image_tag("/assets/images/no_reminder.png", "class": "w-[423px] h-[282px]") %>
  <p class="mt-[28.64px] font-sans font-semibold text-[#767a7b] text-[21px]">No reminders registered so far</p>
</div>

app/views/calendar/show.html.erb
<div class="flex flex-row justify-between items-center">
  <p class="font-sans font-semibold text-2xl text-[#384042]">
    <%= @date_string %>
  </p>
  <a class="btn bg-primary" href="<%= "/reminder/#{@date.month}/#{@date.day}/#{@date.year}/new" %>">
    Add reminder
  </a>
</div>

<div class="flex flex-col mt-[54px] max-h-[510px] -ml-10 px-10 pb-7 scrollbar overflow-x-visible overflow-y-scroll">
  <% date_reminders.map do |reminder| %>
    <div class="flex flex-row shadow-primary bg-white rounded-2xl px-3 relative mt-[30px]">
      <div class="flex rounded-[100px] min-w-[12px] max-w-[12px] my-[12px]" style="background-color: <%= reminder.color %>">&nbsp;</div>
      <div class="flex flex-col grow border-r-[1px] border-[#D1DCF0] w-75 px-[10px] py-[17px] justify-center">
        <p class="font-sans font-semibold text-[14px] text-gray">
          <%= reminder.title %>
        </p>
        <p class="font-sans font-semibold text-[18px] text-[#384042]">
          <%= reminder.description %>
        </p>
      </div>
      <div class="!max-w-[110px] !min-w-[110px] flex flex-col items-center justify-center my-[26px] ml-[10px]">
        <svg width="34" height="34" viewBox="0 0 34 34" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M16.9867 3.1875C9.36328 3.1875 3.1875 9.37656 3.1875 17C3.1875 24.6234 9.36328 30.8125 16.9867 30.8125C24.6234 30.8125 30.8125 24.6234 30.8125 17C30.8125 9.37656 24.6234 3.1875 16.9867 3.1875ZM17 28.05C10.8973 28.05 5.95 23.1027 5.95 17C5.95 10.8973 10.8973 5.95 17 5.95C23.1027 5.95 28.05 10.8973 28.05 17C28.05 23.1027 23.1027 28.05 17 28.05Z" fill="black" fill-opacity="0.5"/>
          <path d="M17.6905 10.0938H15.6187V18.3812L22.8702 22.7309L23.9062 21.0309L17.6905 17.3453V10.0938Z" fill="black" fill-opacity="0.5"/>
        </svg>
        <p class="font-sans font-semibold text-[35px] text-[#797979] leading-[48px]"><%= "#{sprintf("%02d", reminder.scheduled_datetime.hour)}:#{sprintf("%02d", reminder.scheduled_datetime.min)}" %></p>
      </div>
      <a class="w-[36px] h-[36px] absolute -bottom-[18px] -right-[10px] bg-lightsky rounded-full flex items-center justify-center" href="/reminder/<%= reminder.id %>/edit">
        <svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
          <g clip-path="url(#clip0_47_560)">
            <path d="M2.25 15.75H5.0625L13.3575 7.455L10.545 4.6425L2.25 12.9375V15.75ZM3.75 13.56L10.545 6.765L11.235 7.455L4.44 14.25H3.75V13.56ZM13.7775 2.4675C13.7081 2.39797 13.6257 2.34281 13.535 2.30518C13.4442 2.26754 13.347 2.24817 13.2488 2.24817C13.1505 2.24817 13.0533 2.26754 12.9625 2.30518C12.8718 2.34281 12.7894 2.39797 12.72 2.4675L11.3475 3.84L14.16 6.6525L15.5325 5.28C15.602 5.21062 15.6572 5.1282 15.6948 5.03747C15.7325 4.94674 15.7518 4.84948 15.7518 4.75125C15.7518 4.65303 15.7325 4.55576 15.6948 4.46503C15.6572 4.3743 15.602 4.29189 15.5325 4.2225L13.7775 2.4675Z" fill="white"/>
          </g>
          <defs>
            <clipPath id="clip0_47_560">
              <rect width="18" height="18" fill="white"/>
            </clipPath>
          </defs>
        </svg>
      </a>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calendar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" type="image/x-icon" href="/assets/images/favicon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "https://kit.fontawesome.com/8c67ec2d4b.js", crossorigin: "anonymous" %>
    <%= stylesheet_link_tag "http://fonts.cdnfonts.com/css/open-sans" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Lato" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Inter" %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/tw-elements/dist/css/index.min.css" %>

    <%= javascript_include_tag "https://code.jquery.com/jquery-3.6.1.min.js", integrity: "sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=", crossorigin: "anonymous" %>
  </head>

  <body class="bg-[#EBF3FE]">
    <main class="lg:container lg:mx-auto !w-[1120px] mt-[86px] mb-5">
      <div class="flex flex-row">
        <svg width="266" height="43" viewBox="0 0 266 43" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M72.7947 8.25307C75.3692 8.25307 77.8527 8.87323 79.8576 9.8989V15.8144C77.9895 14.5026 75.4376 13.5006 72.8402 13.5006C67.919 13.5006 64.547 17.1025 64.547 21.9208C64.547 26.6675 67.805 30.4123 73.0453 30.4123C75.6882 30.4123 78.1261 29.4582 80.245 27.9556V33.9187C78.0577 35.1353 75.3237 35.6838 72.7947 35.6838C64.6152 35.6838 58.9649 29.7684 58.9649 22.0162C58.9421 14.264 64.6152 8.25307 72.7947 8.25307Z" fill="#3BC6FB"/>
          <path d="M88.174 21.9684C88.174 14.2162 93.8927 8.25307 101.457 8.25307C108.999 8.25307 114.74 14.2162 114.74 21.9684C114.74 29.7206 109.021 35.6838 101.457 35.6838C93.9155 35.6838 88.174 29.7206 88.174 21.9684ZM109.158 21.9684C109.158 17.2694 105.854 13.5484 101.457 13.5484C97.0597 13.5484 93.7559 17.2694 93.7559 21.9684C93.7559 26.6675 97.0597 30.3884 101.457 30.3884C105.854 30.3884 109.158 26.6675 109.158 21.9684Z" fill="#3BC6FB"/>
          <path d="M122.623 8.6348H129.755C139.871 8.6348 145.315 13.3815 145.315 21.9208C145.315 30.0786 140.395 35.2784 129.505 35.2784H122.623V8.6348ZM129.755 30.1501C136.772 30.1501 139.734 27.1684 139.734 21.9208C139.734 19.1301 138.686 16.7686 136.772 15.3852C134.972 14.0732 132.558 13.7632 129.709 13.7632H128.204V30.1739H129.755V30.1501Z" fill="#3BC6FB"/>
          <path d="M153.199 8.6348H168.897V13.7393H158.782V18.9631H167.485V23.829H158.782V30.1501H169.285V35.2545H153.199V8.6348Z" fill="#3BC6FB"/>
          <path d="M176.894 8.6348H182.477V30.1501H193.619V35.2545H176.894V8.6348Z" fill="#3BC6FB"/>
          <path d="M201.501 8.6348H207.084V35.2545H201.501V8.6348Z" fill="#3BC6FB"/>
          <path d="M223.168 13.7632H214.944V8.6348H236.976V13.7393H228.751V35.2545H223.168V13.7632Z" fill="#3BC6FB"/>
          <path d="M251.718 13.7632H243.492V8.6348H265.524V13.7393H257.299V35.2545H251.718V13.7632Z" fill="#3BC6FB"/>
          <path d="M38.9377 12.2603L36.272 7.13199L28.3204 11.6402V9.94667C28.3204 7.20356 27.3862 4.86598 25.5407 2.91005C23.6952 0.977963 21.4397 0 18.7967 0C16.1994 0 13.9665 0.977963 12.121 2.91005C10.2527 4.84212 9.34135 7.20355 9.34135 9.97056V22.4216L0 27.717L2.66568 32.8454L9.31856 29.0527V32.6544C9.31856 35.3975 10.2299 37.7352 12.0754 39.6911C13.9209 41.6471 16.1538 42.6011 18.7967 42.6011C21.4169 42.6011 23.6496 41.6232 25.5179 39.6911C27.3863 37.7591 28.2976 35.3975 28.2976 32.6307V18.295L38.9377 12.2603ZM15.1969 9.8274C15.1969 8.82555 15.5386 7.9907 16.2222 7.29897C16.9056 6.60723 17.7031 6.24945 18.6601 6.24945C19.617 6.24945 20.4144 6.60723 21.0751 7.29897C21.7359 7.9907 22.0777 8.84934 22.0777 9.8274V15.1943L15.1969 19.0823V9.8274ZM22.0777 32.6068C22.0777 33.6086 21.7359 34.4435 21.0751 35.1353C20.4144 35.827 19.5942 36.1847 18.6601 36.1847C17.7031 36.1847 16.9056 35.827 16.2222 35.1353C15.5386 34.4435 15.1969 33.5847 15.1969 32.6068V25.7372L22.0777 21.8254V32.6068Z" fill="#3BC6FB"/>
        </svg>
      </div>

      <div class="flex flex-row mt-[45.4px] rounded-[40px] bg-white shadow-primary">
        <div class="w-[670px] px-10 py-12">
          <%= yield %>
        </div>

        <div class="grow bg-secondary rounded-r-[40px] px-10 py-12">
          <div class="flex flex-col">
            <p class="font-extrabold text-white text-center text-[80px] leading-[109px]">
              <%= @date.year %>
            </p>
            <p class="font-semibold -mt-8 text-white text-center text-[45px] leading-[61px]">
              <%= Date::MONTHNAMES[@date.month] %>
            </p>
          </div>

          <%
            prev_month_day = @date.prev_month(1)
            next_month_day = @date.next_month(1)
          %>
          <div class="flex flex-row mt-[66px] justify-center items-center text-white text-xl font-sans">
            <a href="<%= "/reminder/#{prev_month_day.month}/#{prev_month_day.day}/#{prev_month_day.year}" %>">
              <i class="fa-solid fa-chevron-left"></i>
            </button>
            <a class="bg-[#D9D9D9] w-[6px] h-[6px] ml-[15px] mr-[15px] rounded-full"
              href="<%= "/reminder/#{@today.month}/#{@today.day}/#{@today.year}" %>"></a>
            <a href="<%= "/reminder/#{next_month_day.month}/#{next_month_day.day}/#{next_month_day.year}" %>">
              <i class="fa-solid fa-chevron-right"></i>
            </a>
          </div>

          <div class="container mt-8">
            <div class="flex flex-row text-white">
              <div class="font-lato font-black text-xs basis-1/7 text-center">
                SUN
              </div>
              <div class="font-lato font-black text-xs basis-1/7 text-center">
                MON
              </div>
              <div class="font-lato font-black text-xs basis-1/7 text-center">
                TUE
              </div>
              <div class="font-lato font-black text-xs basis-1/7 text-center">
                WED
              </div>
              <div class="font-lato font-black text-xs basis-1/7 text-center">
                THU
              </div>
              <div class="font-lato font-black text-xs basis-1/7 text-center">
                FRI
              </div>
              <div class="font-lato font-black text-xs basis-1/7 text-center">
                SAT
              </div>
            </div>

            <%
              month_index = 0
              wday_index = @first_day_wday
              days = Time.days_in_month(@date.month, @date.year)
            %>

            <div class="flex flex-row text-white mt-4">
            <% for i in 0...@first_day_wday %>
              <div class="font-lato font-medium text-lg basis-1/7 text-center">
              </div>
            <% end %>
            <% days.times do |i| %>
              <div class="flex font-lato font-medium text-lg basis-1/7 justify-center">
                <a class="!w-[36px] !h-[36px] flex justify-center items-center <%= (i + 1) == @date.day ? "rounded-full bg-primary" : "" %>"
                    href="<%= "/reminder/#{@date.month}/#{i+1}/#{@date.year}" %>">
                  <% if @reminder_days.include?(i + 1) %>
                    <span class="relative">
                      <%= i + 1 %>
                      <div class="absolute w-1.5 h-1.5 top-0 -right-2 bg-green rounded-full"></div>
                    </span>
                  <% else %>
                    <%= i + 1 %>
                  <% end %>
                </span>
                </a>
              </div>
              <% wday_index += 1 %>
              <% if wday_index % 7 == 0 %>
                </div>
                <div class="flex flex-row text-white mt-4">
              <% end %>
            <% end %>
          </div>
          <div class="flex mt-[63px] font-inter justify-center text-xs font-normal text-white">
            &copy; <%= @today.year %> Codelitt Inc All rights reserved
          </div>
        </div>
      </div>
    </main>

    <%= javascript_include_tag "https://cdn.jsdelivr.net/npm/tw-elements/dist/js/index.min.js" %>
    <%= javascript_include_tag "javascripts/application.js" %>
  </body>
</html>